### PR TITLE
Fix code style

### LINKED ISSUE #44: Adjust code to Node style guideline
https://github.com/nodejs/node/blob/master/CPP_STYLE_GUIDE.md
https://github.com/nodejs/node/blob/master/doc/STYLE_GUIDE.md

### PR DESCRIPTION
**Pull request by luminosuslight**
Using Node code style guidelines.

Closes #44 (could be kept open as a reminder for later code changes).

### CODE REVIEW

**Comment by cmfcmf** [comment]
The linter is still producing a bunch of errors, even with this PR, here's the first few:
```
cmfcmf@CHRISTIAN-SURFA:/mnt/c/Users/cmfcm/Desktop/node-embed/externals/node-v9.0.0$ make lint-cpp
Running C++ linter...
src/node.cc:4802:  Is this a non-const reference? If so, make const or use a pointer: Environment & env  [runtime/references] [2]
src/node.cc:4822:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node.cc:5001:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
src/node.cc:5002:  public: should be indented +1 space inside class CmdArgs  [whitespace/indent] [3]
src/node.cc:5014:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node.cc:5019:  Missing space around colon in range-based for loop  [whitespace/forcolon] [2]
src/node.cc:5027:  Using deprecated casting style.  Use static_cast<char>(...) instead  [readability/casting] [4]
src/node.cc:5028:  Missing space around colon in range-based for loop  [whitespace/forcolon] [2]
src/node.cc:5031:  Using deprecated casting style.  Use static_cast<char>(...) instead  [readability/casting] [4]
src/node.cc:5035:  Missing spaces around <  [whitespace/operators] [3]
src/node.cc:5054:  private: should be indented +1 space inside class CmdArgs  [whitespace/indent] [3]
src/node.cc:5096:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
src/node.cc:5101:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
```

**Comment by cmfcmf** [comment]
While you're at it: The `node_lib.h` file is currently using `CRLF`, make sure to change it to `LF`.

**Comment by luminosuslight** [comment]
This should now be ready to be merged, please review the 496 changes :octocat: 😄 

And have a close look at node_lib.h, I had to merge this by hand.

**Comment by luminosuslight** [comment]
The remaining linter problem will be addressed in #59.

**Pull request merged**
